### ISSUE TITLE
Forum post replies are broken

### ISSUE THREAD

**Issue by maxiscool69** [RishabSwift/Falcon#1]
Forum post replies when using falcon are broken. They come back as entirely blank, which is super annoying since I just realized I've been writing blank shit and have no marks. 

The message at the bottom of the thread was written with Falcon disabled, others with it enabled. 

https://imgur.com/a/100vPwm

**Comment by RishabSwift** [comment]
Thanks for reporting this issue!
I was able to recreate it and have identified the issue. I'll issue a fix for version 1.0.3.

**Comment by RishabSwift** [comment]
This has been resolved
